### ISSUE TITLE
Demo Down

### ISSUE THREAD

**Issue by jlpoolen** [ritzyed/ritzy-demo#1]
The Documentation invites users to try a Demo at http://demo-ritzy.rhcloud.com/ but the link does not successfully resolve.

**Comment by jlpoolen** [comment]
For posterity, here's the text:

>#  Ritzy Editor Demo

>A demo of the Ritzy collaborative real-time browser-based editor. The demo is generally up and running at:

>http://demo-ritzy.rhcloud.com/

**Comment by jeffreyschultz** [comment]
The domain is no longer registered. Also, the project no longer builds because of an issue with nan it seems.

**Comment by jlpoolen** [comment]
What is "nan" in your phrase:

> because of an issue with nan it seems

**Comment by jeffreyschultz** [comment]
Native Abstractions for Node.js

https://github.com/nodejs/nan

```

> bufferutil@1.1.0 install /Users/jschultz/Source/ritzyed/ritzy-demo/node_modules/bufferutil
> node-gyp rebuild

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
In file included from ../src/bufferutil.cc:16:
In file included from ../node_modules/nan/nan.h:82:
../node_modules/nan/nan_new.h:24:43: error: no member named 'Handle' in namespace 'v8'
template <typename T> v8::Local<T> To(v8::Handle<v8::Integer> i);
                                      ~~~~^
../node_modules/nan/nan_new.h:24:61: error: expected '(' for function-style cast or type construction
template <typename T> v8::Local<T> To(v8::Handle<v8::Integer> i);
                                                 ~~~~~~~~~~~^
../node_modules/nan/nan_new.h:24:63: error: use of undeclared identifier 'i'
template <typename T> v8::Local<T> To(v8::Handle<v8::Integer> i);
                                                              ^
../node_modules/nan/nan_new.h:29:21: error: no template named 'Handle' in namespace 'v8'
To<v8::Integer>(v8::Handle<v8::Integer> i) { return i->ToInteger(); }
                ~~~~^
../node_modules/nan/nan_new.h:34:19: error: no template named 'Handle' in namespace 'v8'
To<v8::Int32>(v8::Handle<v8::Integer> i)   { return i->ToInt32(); }
              ~~~~^
../node_modules/nan/nan_new.h:39:20: error: no template named 'Handle' in namespace 'v8'
To<v8::Uint32>(v8::Handle<v8::Integer> i)  { return i->ToUint32(); }
               ~~~~^
../node_modules/nan/nan_new.h:66:12: error: no template named 'Handle' in namespace 'v8'
     , v8::Handle<v8::ObjectTemplate> tmpl = v8::Handle<v8::ObjectTemplate>()
       ~~~~^
../node_modules/nan/nan_new.h:67:12: error: no template named 'Handle' in namespace 'v8'
     , v8::Handle<v8::Value> obj = v8::Handle<v8::Value>());
       ~~~~^
../node_modules/nan/nan_new.h:66:50: error: no member named 'Handle' in namespace 'v8'
     , v8::Handle<v8::ObjectTemplate> tmpl = v8::Handle<v8::ObjectTemplate>()
                                             ~~~~^
../node_modules/nan/nan_new.h:66:75: error: expected '(' for function-style cast or type construction
     , v8::Handle<v8::ObjectTemplate> tmpl = v8::Handle<v8::ObjectTemplate>()
                                                        ~~~~~~~~~~~~~~~~~~^
../node_modules/nan/nan_new.h:66:77: error: expected expression
     , v8::Handle<v8::ObjectTemplate> tmpl = v8::Handle<v8::ObjectTemplate>()
                                                                            ^
../node_modules/nan/nan_new.h:67:40: error: no member named 'Handle' in namespace 'v8'
     , v8::Handle<v8::Value> obj = v8::Handle<v8::Value>());
                                   ~~~~^
../node_modules/nan/nan_new.h:67:56: error: expected '(' for function-style cast or type construction
     , v8::Handle<v8::Value> obj = v8::Handle<v8::Value>());
                                              ~~~~~~~~~^
../node_modules/nan/nan_new.h:67:58: error: expected expression
     , v8::Handle<v8::Value> obj = v8::Handle<v8::Value>());
                                                         ^
../node_modules/nan/nan_new.h:85:12: error: no template named 'Handle' in namespace 'v8'
     , v8::Handle<v8::Value> data = v8::Handle<v8::Value>());
       ~~~~^
../node_modules/nan/nan_new.h:85:41: error: no member named 'Handle' in namespace 'v8'
     , v8::Handle<v8::Value> data = v8::Handle<v8::Value>());
                                    ~~~~^
../node_modules/nan/nan_new.h:85:57: error: expected '(' for function-style cast or type construction
     , v8::Handle<v8::Value> data = v8::Handle<v8::Value>());
                                               ~~~~~~~~~^
../node_modules/nan/nan_new.h:85:59: error: expected expression
     , v8::Handle<v8::Value> data = v8::Handle<v8::Value>());
                                                          ^
../node_modules/nan/nan_new.h:93:12: error: no template named 'Handle' in namespace 'v8'
     , v8::Handle<v8::Value> data = v8::Handle<v8::Value>()
       ~~~~^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/bufferutil/src/bufferutil.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Darwin 19.4.0
gyp ERR! command "/usr/local/Cellar/node/14.2.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/jschultz/Source/ritzyed/ritzy-demo/node_modules/bufferutil
gyp ERR! node -v v14.2.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 

> utf-8-validate@1.1.0 install /Users/jschultz/Source/ritzyed/ritzy-demo/node_modules/utf-8-validate
> node-gyp rebuild

  CXX(target) Release/obj.target/validation/src/validation.o
In file included from ../src/validation.cc:15:
In file included from ../node_modules/nan/nan.h:82:
../node_modules/nan/nan_new.h:24:43: error: no member named 'Handle' in namespace 'v8'
template <typename T> v8::Local<T> To(v8::Handle<v8::Integer> i);
                                      ~~~~^
../node_modules/nan/nan_new.h:24:61: error: expected '(' for function-style cast or type construction
template <typename T> v8::Local<T> To(v8::Handle<v8::Integer> i);
                                                 ~~~~~~~~~~~^
../node_modules/nan/nan_new.h:24:63: error: use of undeclared identifier 'i'
template <typename T> v8::Local<T> To(v8::Handle<v8::Integer> i);
                                                              ^
../node_modules/nan/nan_new.h:29:21: error: no template named 'Handle' in namespace 'v8'
To<v8::Integer>(v8::Handle<v8::Integer> i) { return i->ToInteger(); }
                ~~~~^
../node_modules/nan/nan_new.h:34:19: error: no template named 'Handle' in namespace 'v8'
To<v8::Int32>(v8::Handle<v8::Integer> i)   { return i->ToInt32(); }
              ~~~~^
../node_modules/nan/nan_new.h:39:20: error: no template named 'Handle' in namespace 'v8'
To<v8::Uint32>(v8::Handle<v8::Integer> i)  { return i->ToUint32(); }
               ~~~~^
../node_modules/nan/nan_new.h:66:12: error: no template named 'Handle' in namespace 'v8'
     , v8::Handle<v8::ObjectTemplate> tmpl = v8::Handle<v8::ObjectTemplate>()
       ~~~~^
../node_modules/nan/nan_new.h:67:12: error: no template named 'Handle' in namespace 'v8'
     , v8::Handle<v8::Value> obj = v8::Handle<v8::Value>());
       ~~~~^
../node_modules/nan/nan_new.h:66:50: error: no member named 'Handle' in namespace 'v8'
     , v8::Handle<v8::ObjectTemplate> tmpl = v8::Handle<v8::ObjectTemplate>()
                                             ~~~~^
../node_modules/nan/nan_new.h:66:75: error: expected '(' for function-style cast or type construction
     , v8::Handle<v8::ObjectTemplate> tmpl = v8::Handle<v8::ObjectTemplate>()
                                                        ~~~~~~~~~~~~~~~~~~^
../node_modules/nan/nan_new.h:66:77: error: expected expression
     , v8::Handle<v8::ObjectTemplate> tmpl = v8::Handle<v8::ObjectTemplate>()
                                                                            ^
../node_modules/nan/nan_new.h:67:40: error: no member named 'Handle' in namespace 'v8'
     , v8::Handle<v8::Value> obj = v8::Handle<v8::Value>());
                                   ~~~~^
../node_modules/nan/nan_new.h:67:56: error: expected '(' for function-style cast or type construction
     , v8::Handle<v8::Value> obj = v8::Handle<v8::Value>());
                                              ~~~~~~~~~^
../node_modules/nan/nan_new.h:67:58: error: expected expression
     , v8::Handle<v8::Value> obj = v8::Handle<v8::Value>());
                                                         ^
../node_modules/nan/nan_new.h:85:12: error: no template named 'Handle' in namespace 'v8'
     , v8::Handle<v8::Value> data = v8::Handle<v8::Value>());
       ~~~~^
../node_modules/nan/nan_new.h:85:41: error: no member named 'Handle' in namespace 'v8'
     , v8::Handle<v8::Value> data = v8::Handle<v8::Value>());
                                    ~~~~^
../node_modules/nan/nan_new.h:85:57: error: expected '(' for function-style cast or type construction
     , v8::Handle<v8::Value> data = v8::Handle<v8::Value>());
                                               ~~~~~~~~~^
../node_modules/nan/nan_new.h:85:59: error: expected expression
     , v8::Handle<v8::Value> data = v8::Handle<v8::Value>());
                                                          ^
../node_modules/nan/nan_new.h:93:12: error: no template named 'Handle' in namespace 'v8'
     , v8::Handle<v8::Value> data = v8::Handle<v8::Value>()
       ~~~~^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/validation/src/validation.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Darwin 19.4.0
gyp ERR! command "/usr/local/Cellar/node/14.2.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/jschultz/Source/ritzyed/ritzy-demo/node_modules/utf-8-validate
gyp ERR! node -v v14.2.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 

> ritzy-demo@0.1.4 install /Users/jschultz/Source/ritzyed/ritzy-demo
> gulp build

fs.js:39
} = primordials;
    ^

ReferenceError: primordials is not defined
    at fs.js:39:5
    at req_ (/Users/jschultz/Source/ritzyed/ritzy-demo/node_modules/natives/index.js:143:24)
    at Object.req [as require] (/Users/jschultz/Source/ritzyed/ritzy-demo/node_modules/natives/index.js:55:10)
    at Object.<anonymous> (/Users/jschultz/Source/ritzyed/ritzy-demo/node_modules/vinyl-fs/node_modules/graceful-fs/fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:1176:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1196:10)
    at Module.load (internal/modules/cjs/loader.js:1040:32)
    at Function.Module._load (internal/modules/cjs/loader.js:929:14)
    at Module.require (internal/modules/cjs/loader.js:1080:19)
    at require (internal/modules/cjs/helpers.js:72:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ritzy-demo@0.1.4 install: `gulp build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ritzy-demo@0.1.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jschultz/.npm/_logs/2020-05-15T13_01_42_875Z-debug.log

```

**Comment by zheddie** [comment]
@jeffreyschultz , I also hit this similar issue locally in my node10 docker . I tried to change the dependencies of ws from 0.xx to "^1.1.5". The build issue disappear. While , when I do the "npm run" , I got following output:
```
Lifecycle scripts included in ritzy-demo:
  test
    echo "Error: no test specified" && exit 1
  install
    gulp build
  start
    node build/server.js
```
Looks like we can only do npm test/install/start.  I am interest in the "start". While , looks like we can not find the build/server.js, while I can only get src/server.js. When I tried to do the "node src/server.js" it failed with following error:
```
/root/myapps/ritzy-demo/src/server.js:1
import 'babel/polyfill'
       ^^^^^^^^^^^^^^^^

SyntaxError: Unexpected string
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
```
😢
